In [1]:
import numpy as np

In [8]:
#  matrix 2d de formato 3 por 3
matrix_consumo = np.array([[200, 120, 70], [150, 90, 50], [300, 150, 90]])

# vetor array 1d
v_calory = np.array([4, 4, 9])

# calculando calorias vetorização e broadcasting
#broadcasting para multiplicar cada linha de matrix_consumo pelo elemento correspondente de v_calory
# matrix_consumo tem formato (3, 3) e v_calory tem formato (3,), usando np.newaxis para transformar v_calory em (3, 1)
antes = matrix_consumo * v_calory
print(antes)
print(10 * '/')
matrix_detalhada = matrix_consumo * v_calory[:, np.newaxis].copy()
print(matrix_detalhada)


[[ 800  480  630]
 [ 600  360  450]
 [1200  600  810]]
//////////
[[ 800  480  280]
 [ 600  360  200]
 [2700 1350  810]]


In [10]:
# totalizando calorias por linha tipo 800+480+280=1560
total_calorias = matrix_detalhada.sum(axis=1)
print(total_calorias)

[1560 1160 4860]


In [19]:
# agregação de numpy para calcular a média de calorias por refeição de cada coluna
media_calorias = matrix_detalhada.mean(axis=0) # axis 0 para calcular a média por coluna (refeição)
print(media_calorias)

[1366.66666667  730.          430.        ]


In [ ]:
# correção do erro, criando um vetor de formato (3, 1) para multiplicar corretamente
v_calory_reshaped = v_calory[:, np.newaxis] # agora v_calory_reshaped tem formato (3, 1) e pode ser multiplicado corretamente com matrix_consumo
matrix_detalhada_corrected = matrix_consumo * v_calory_reshaped # aqui a multiplicação é feita corretamente, resultando em uma matriz detalhada de calorias
print(matrix_detalhada_corrected)

[[ 800  480  280]
 [ 600  360  200]
 [2700 1350  810]]


In [21]:
# de cada coluna coluna de cada usuário, calculando a média de linha e de colunas
mediageral = matrix_detalhada_corrected.mean(axis=0) # média por coluna (refeição)
print(mediageral)
media_de_linha = matrix_detalhada_corrected.mean(axis=1) # média por linha (usuário)
print(media_de_linha)


[1366.66666667  730.          430.        ]
[ 520.          386.66666667 1620.        ]


In [17]:
mediageral = matrix_detalhada_corrected.mean()
print(mediageral)

842.2222222222222
